/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DemoDeploy } from "./DemoDeploy";
export type { LoanAgentFactoryDeploy } from "./LoanAgentFactoryDeploy";
export type { MockMinerDeploy } from "./MockMinerDeploy";
