/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IStats, IStatsInterface } from "../IStats";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "loanAgent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "poolID",
        type: "uint256",
      },
    ],
    name: "hasPenalties",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "loanAgent",
        type: "address",
      },
    ],
    name: "hasPenalties",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "loanAgent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "poolID",
        type: "uint256",
      },
    ],
    name: "isDebtor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "loanAgent",
        type: "address",
      },
    ],
    name: "isDebtor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "loanAgent",
        type: "address",
      },
    ],
    name: "isLoanAgent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStats__factory {
  static readonly abi = _abi;
  static createInterface(): IStatsInterface {
    return new utils.Interface(_abi) as IStatsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IStats {
    return new Contract(address, _abi, signerOrProvider) as IStats;
  }
}
