/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILoanAgentFactory } from "./ILoanAgentFactory";
export type { LoanAgentFactory } from "./LoanAgentFactory";
