/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LoanAgentBasicTest } from "./LoanAgentBasicTest";
export type { LoanAgentTest } from "./LoanAgentTest";
