/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMiner__factory } from "./IMiner__factory";
export { MockMiner__factory } from "./MockMiner__factory";
