[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solce_version = "0.8.15"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "solmate/=lib/solmate/src/",
  "gcred/=src/"
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
