/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LoanAgentBasicTest__factory } from "./LoanAgentBasicTest__factory";
export { LoanAgentTest__factory } from "./LoanAgentTest__factory";
