/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILoanAgentFactory,
  ILoanAgentFactoryInterface,
} from "../../LoanAgentFactory.sol/ILoanAgentFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "miner",
        type: "address",
      },
    ],
    name: "activeMiners",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_miner",
        type: "address",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "loanAgent",
        type: "address",
      },
    ],
    name: "loanAgents",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILoanAgentFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ILoanAgentFactoryInterface {
    return new utils.Interface(_abi) as ILoanAgentFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILoanAgentFactory {
    return new Contract(address, _abi, signerOrProvider) as ILoanAgentFactory;
  }
}
