/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILoanAgentFactory__factory } from "./ILoanAgentFactory__factory";
export { LoanAgentFactory__factory } from "./LoanAgentFactory__factory";
