/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface IStatsInterface extends utils.Interface {
  functions: {
    "hasPenalties(address,uint256)": FunctionFragment;
    "hasPenalties(address)": FunctionFragment;
    "isDebtor(address,uint256)": FunctionFragment;
    "isDebtor(address)": FunctionFragment;
    "isLoanAgent(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "hasPenalties(address,uint256)"
      | "hasPenalties(address)"
      | "isDebtor(address,uint256)"
      | "isDebtor(address)"
      | "isLoanAgent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hasPenalties(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPenalties(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isDebtor(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isDebtor(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isLoanAgent",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "hasPenalties(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPenalties(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDebtor(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDebtor(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLoanAgent",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IStats extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStatsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    "hasPenalties(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "hasPenalties(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "isDebtor(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "isDebtor(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isLoanAgent(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  "hasPenalties(address,uint256)"(
    loanAgent: PromiseOrValue<string>,
    poolID: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "hasPenalties(address)"(
    loanAgent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "isDebtor(address,uint256)"(
    loanAgent: PromiseOrValue<string>,
    poolID: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "isDebtor(address)"(
    loanAgent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isLoanAgent(
    loanAgent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "hasPenalties(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasPenalties(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isDebtor(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isDebtor(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isLoanAgent(
      loanAgent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    "hasPenalties(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "hasPenalties(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "isDebtor(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "isDebtor(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isLoanAgent(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "hasPenalties(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "hasPenalties(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "isDebtor(address,uint256)"(
      loanAgent: PromiseOrValue<string>,
      poolID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "isDebtor(address)"(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isLoanAgent(
      loanAgent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
